### ISSUE TITLE
[TW/PBRP]Reboot to EDL doesn't work

### ISSUE THREAD

**Issue by masemoel** [Redmi-K30-5G/device_xiaomi_picasso_recovery#1]
(Happens on both TWRP and PBRP).
In the **Reboot** menu, the option **Reboot to EDL** is not working: it reboots to system.

**Comment by Hadenix** [comment]
> (Happens on both TWRP and PBRP).
> In the **Reboot** menu, the option **Reboot to EDL** is not working: it reboots to system.

I haven't even tested it

**Comment by Hadenix** [comment]
checked, goes to the system. I think that the code is not adapted yet normally for 10 android
