### ISSUE TITLE
The mount of /sdcard is missing

### ISSUE THREAD

**Issue by meixiaofei** [Redmi-K30-5G/device_xiaomi_picasso_recovery#6]
Thus, the space can use is very small.

![image](https://user-images.githubusercontent.com/20218180/102488870-a82a6980-40a7-11eb-9dbc-5fbe5d557182.png)

**Comment by Hadenix** [comment]
> Thus, the space can use is very small.
> 
> ![образ](https://user-images.githubusercontent.com/20218180/102488870-a82a6980-40a7-11eb-9dbc-5fbe5d557182.png)

added to twrp and everything works try the latest version and let me know if everything is good https://hadenix.github.io/twrp-3.4.x-picasso/

**Comment by masemoel** [comment]
Why would you want /sdcard? Picasso doesn't have SD card slot.

**Comment by meixiaofei** [comment]
> Why would you want /sdcard? Picasso doesn't have SD card slot.

Thanks for reply.
Because I found that all user's file is store in this dir, maybe just a illusion🤣
1. under the recovery mode
  I want to send a rom file which size is grater then 3GB,
just use the command ```adb push zip-file-path-on-computer /sdcard ```
then at the end of progress, it return a tip like "there is no enough space on the device"
**should i replace the target place from /sdcard to /?** 
2. after the system boot as normal **just ignore because can not reappear**
In some apps, could not use the storage, include google play.
on play: can not download any app(have no tip short of space), just always pending
on wechat: while use disk(see user's profile) have a tips that could not found a storage
