### ISSUE TITLE
Can you help me write another example of TWRP

### ISSUE THREAD

**Issue by java67** [Redmi-K30-5G/device_xiaomi_picasso_recovery#7]
Can you help me write another example of TWRP

Because my model does not have TWRP fastboot, it is troublesome to flash, thank you

**Comment by masemoel** [comment]
Hey man,

**Comment by java67** [comment]
> 嘿，
> 您是哪个模特？顺便说一句，我不完全理解您的问题……您_以TWRP为例_意味着什么？
oneplus8t  KB2000      Code: kebab

**Comment by java67** [comment]
oneplus8t    KB2000         ：kebab

**Comment by masemoel** [comment]
That's not related to picasso, so I will close this issue.
Where is your device tree for TWRP? I cannot see any tree in your Git profile...
You can have a look at the tree of hotdog, and start adapting the fork you made of my tree...
https://github.com/mauronofrio/android_device_oneplus_hotdog_unified_TWRP

**Comment by masemoel** [comment]
Btw if your device is A/B, you should boot the boot.img, not the recovery.img, so you should use the lunch omni_kebab-eng && mka bootimage  command.

**Comment by java67** [comment]
> Btw if your device is A/B, you should boot the boot.img, not the recovery.img, so you should use the lunch omni_kebab-eng && mka bootimage command.
 Our device factory Android 11
https://github.com/mauronofrio/android_device_oneplus_instantnoodle_TWRP  oneplus 8T a/b   Almost 8p
