### ISSUE TITLE
Help me see if there are any corrections, there is a recovery official website for h2

### ISSUE THREAD

**Issue by java67** [Redmi-K30-5G/device_xiaomi_picasso_recovery#8]
https://github.com/java67/device_oneplus_kebab_TWRP_test        （I changed it myself, the TWRP interface will have a flashing screen, which improves TWRP）Thank you！

**Comment by masemoel** [comment]
I see you adapted the tree from the Xiaomi Mi 10, although you left some stuff like the product name in omni_kebab.mk
I suggest basing (or, at least, having a look) at OnePlus 8 TWRP device tree, specially for the fstabs, as they are different to Xiaomi's ones ( see https://github.com/mauronofrio/android_device_oneplus_instantnoodle_TWRP/tree/android-10.0/recovery/root/system/etc )
Finally, ensure to use kebab blobs in /recovery/root/vendor , and copy the A/B related flags from the previous tree to yours. Then, try building and tell me your result ;)

**Comment by masemoel** [comment]
Ah, and please, do NOT open a new issue. Follow the conversation here, okay?
